### ISSUE TITLE
Display all labels in Virtuoso FCT

### ISSUE THREAD

**Issue by pasqLisena** [silknow/knowledge-base#2]
Hello, I just realised that in the facet browser I am not able to see all labels.
For example [here](https://data.silknow.org/production/d3385864-8350-3915-bbed-1aaf99cb0162), I don't see the Spanish labels in `P125 used object of type` and `P32 used general technique` (even if they are there in the turtle).

This is normally a procedure to follow (see the [wiki](http://semantics.eurecom.fr/wiki/Tools#How_to_display_multilingual_labels_in_FCT_browser)), but I have an error when trying to follow it using Virtuoso's Conductor.
For sure there is a way to enable it from the command line (to be included in our build script).

**Comment by rtroncy** [comment]
Has the procedure/documentation of Virtuoso changed in the latest version? I haven't checked. But it would be good to either update the howto documentation in the wiki and/or provide an alternative set of instructions we could include in the loading script.

**Comment by pasqLisena** [comment]
The procedure is valid.
I think there is something missing in our conductor (a missing library or something), that makes it crash when accessing the Web Application Server tab.

Anyway it should exist the command line version

**Comment by ehrhart** [comment]
I have updated the facet browser package with one which already includes the fix to display all labels by default. 
@pasqLisena can you please confirm that the labels are correctly being displayed?

I also created a new issue for the conductor error: #3

**Comment by pasqLisena** [comment]
I confirm (so we can close this issue)
